---
spec/acceptance/nodesets/centos-511-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-72-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-78-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-82-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  delete: true
.travis.yml:
  secure: "BupP3afJjFERXGk438ep3EZBqw1xeKN/PgYOje7pWljgrog16lXE7u4UrcUtzYnq31RH0CfSjmqNaUi6gEk0GEbJHDKHw2IwzUEd0oDgsafoHpoCiLgEe79IzUZ7tmuZ01mmrhzmgm34NhDkSspS2MPIU2ngxzAvXqlz4zsrm48="
